### ISSUE TITLE
java.lang.NoClassDefFoundError thrown for 3rd party installation referrer

### ISSUE THREAD

**Issue by mateot1** [BranchMetrics/android-branch-deep-linking-attribution#1040]
### Describe the bug

So far this is only breaking tests on CI since we have at least one test that executes Branch initialization in a robolectric test, but it makes me think it could happen in production. 

```
java.lang.NoClassDefFoundError: com/huawei/hms/ads/installreferrer/api/InstallReferrerStateListener
	at io.branch.referral.Branch.registerAppInit(Branch.java:1958)
	at io.branch.referral.Branch.initializeSession(Branch.java:1886)
	at io.branch.referral.Branch.access$600(Branch.java:77)
	at io.branch.referral.Branch$InitSessionBuilder.init(Branch.java:3168)
```

This is exception is thrown on line 1958 of `Branch.java` from calling `StoreReferrerHuaweiAppGallery.erroredOut`. The check should likely be `if (waitingForHuaweiInstallReferrer && StoreReferrerHuaweiAppGallery.erroredOut)` to prevent from invoking this if the dependency does not exist. This is also likely true for the checks following this one (Samsung and Xiaomi). 

### Steps to reproduce

1. Do not include the Huawei referrer dependency in your build 
2. Create a robolectric test or some other environment where all attribution attempts will fail
3. Exception is thrown since subsequent `erroredOut` checks do not also check if appropriate classes exist. 

### Expected behavior

The check should not happen or fail silently without crashing. 

### SDK Version

5.2.7 (probably introduced in 5.2.0)

### Make and Model

Robolectric 

### OS

12

**Comment by gdeluna-branch** [comment]
Thanks for reporting this, I'll take a look asap.

**Comment by gdeluna-branch** [comment]
Hey @mateot1 

So `waitingForHuaweiInstallReferrer` is set to `true` by the block:

```
 if (classExists("com.huawei.hms.ads.installreferrer.api.InstallReferrerClient")
                && !StoreReferrerHuaweiAppGallery.hasBeenUsed) {
                    waitingForHuaweiInstallReferrer = true;
                    request.addProcessWaitLock(ServerRequest.PROCESS_WAIT_LOCK.HUAWEI_INSTALL_REFERRER_FETCH_WAIT_LOCK);
                }

```
right above.  All are false by default. That boolean is then checked to invoke that client. But a related class was not found, causing this error.

Would you be able to provide some Branch SDK logs? To enable call `Branch.enableLogging();` in your robolectric test application `onCreate()` just before calling         `Branch.getAutoInstance(this);` That'll help me see more closely where this went wrong.

Thanks!

**Comment by mateot1** [comment]
@gdeluna-branch so in the if check you referenced, `StoreReferrerHuaweiAppGallery.hasBeenUsed` doesn't get called because that previous `classExists` check is false. This crash is happening later with this `erroredOut` check:
```
if (StoreReferrerHuaweiAppGallery.erroredOut) {
  request.removeProcessWaitLock(ServerRequest.PROCESS_WAIT_LOCK.HUAWEI_INSTALL_REFERRER_FETCH_WAIT_LOCK);
}
```

I was suggesting that if you updated that check to also include the boolean (which will be false as you said), it might fix the issue:
```
if (waitingForHuaweiInstallReferrer && StoreReferrerHuaweiAppGallery.erroredOut) {
  request.removeProcessWaitLock(ServerRequest.PROCESS_WAIT_LOCK.HUAWEI_INSTALL_REFERRER_FETCH_WAIT_LOCK);
}
```

Unfortunately I'm having trouble reproducing the issue in isolation without running the full test suite on CI... it happens later in an unrelated test (probably waiting for the google play store referrer lock?). Also for what it's worth we're using this sdk via https://github.com/mparticle-integrations/mparticle-android-integration-branchmetrics so it adds another layer of obfuscation, but I don't think it's their wrapper causing the issue.

**Comment by mateot1** [comment]
hello, I found out that we are actually no longer a client, so feel free to deprioritize this if we're the only one who ran into it. thanks.

**Comment by gabrieldl** [comment]
Appreciate the response! This is a good indicator to us to expand our testing coverage at least.

Thanks

**Comment by gdeluna-branch** [comment]
Appreciate the response! This is a good indicator for us to expand our testing coverage at least.

Thanks

**Comment by cooperkong** [comment]
Hi @gdeluna-branch we are facing similar issues when running Robolectric tests.
```
com/huawei/hms/ads/installreferrer/api/InstallReferrerStateListenerjava.lang.NoClassDefFoundError: com/huawei/hms/ads/installreferrer/api/InstallReferrerStateListener
	at io.branch.referral.StoreReferrerUtils.getLatestValidReferrerStore(StoreReferrerUtils.java:29)
	at io.branch.referral.Branch.tryProcessNextQueueItemAfterInstallReferrer(Branch.java:1078)
	at io.branch.referral.Branch.onGoogleInstallReferrerEventsFinished(Branch.java:1052)
	at io.branch.referral.StoreReferrerGooglePlayStore.reportInstallReferrer(StoreReferrerGooglePlayStore.java:92)
	at io.branch.referral.StoreReferrerGooglePlayStore.onReferrerClientError(StoreReferrerGooglePlayStore.java:87)```

checking Google Play store will obvisouly fail in test environment then it goes to `tryProcessNextQueueItemAfterInstallReferrer` which checks for all the rest of the store in 

```
 StoreReferrerUtils.getLatestValidReferrerStore();
```
this where it will crash because it's lacking 3rd party dependencies, whereas it probably works fine on real devices.

**Comment by bolot** [comment]
We are also running into this in Robolectric tests. As a result, we cannot upgrade from Branch 5.1.x to 5.2.x or 5.3.0.

```
com/huawei/hms/ads/installreferrer/api/InstallReferrerStateListener
java.lang.NoClassDefFoundError: com/huawei/hms/ads/installreferrer/api/InstallReferrerStateListener
	at io.branch.referral.StoreReferrerUtils.getLatestValidReferrerStore(StoreReferrerUtils.java:29)
	at io.branch.referral.Branch.tryProcessNextQueueItemAfterInstallReferrer(Branch.java:1098)
	at io.branch.referral.Branch.onGoogleInstallReferrerEventsFinished(Branch.java:1072)
	at io.branch.referral.StoreReferrerGooglePlayStore.reportInstallReferrer(StoreReferrerGooglePlayStore.java:92)
	at io.branch.referral.StoreReferrerGooglePlayStore.onReferrerClientError(StoreReferrerGooglePlayStore.java:87)
	at io.branch.referral.StoreReferrerGooglePlayStore.access$000(StoreReferrerGooglePlayStore.java:13)
	at io.branch.referral.StoreReferrerGooglePlayStore$1.onInstallReferrerSetupFinished(StoreReferrerGooglePlayStore.java:62)
	at com.android.installreferrer.api.InstallReferrerClientImpl.startConnection(InstallReferrerClientImpl.java:16)
	at io.branch.referral.StoreReferrerGooglePlayStore.fetch(StoreReferrerGooglePlayStore.java:28)
	at io.branch.referral.Branch.registerAppInit(Branch.java:1988)
	at io.branch.referral.Branch.initializeSession(Branch.java:1936)
	at io.branch.referral.Branch.access$600(Branch.java:76)
	at io.branch.referral.Branch$InitSessionBuilder.init(Branch.java:3231)
	at io.branch.referral.BranchActivityLifecycleObserver.onActivityResumed(BranchActivityLifecycleObserver.java:73)
	at android.app.Application.dispatchActivityResumed(Application.java:239)
	at android.app.Activity.onResume(Activity.java:1343)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:310)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnResume(RoboMonitoringInstrumentation.java:313)
	at android.app.Activity.performResume(Activity.java:7292)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at org.robolectric.shadows._Activity_$$Reflector58.performResume(Unknown Source)
	at org.robolectric.android.controller.ActivityController.lambda$resume$5(ActivityController.java:187)
	at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:204)
	at org.robolectric.android.controller.ComponentController.invokeWhilePaused(ComponentController.java:64)
	at org.robolectric.android.controller.ActivityController.resume(ActivityController.java:182)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.startActivitySyncInternal(RoboMonitoringInstrumentation.java:116)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:35)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:40)
	at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:362)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:235)
	at androidx.fragment.app.testing.FragmentScenario$Companion.internalLaunch$fragment_testing_release(FragmentScenario.kt:590)
	at androidx.fragment.app.testing.FragmentScenario$Companion.launchInContainer(FragmentScenario.kt:561)
	at tv.caffeine.app.ui.UITests.init(UITests.kt:0)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:580)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:287)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: org.robolectric.android.internal.AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.
Caused by: java.lang.ClassNotFoundException: com.huawei.hms.ads.installreferrer.api.InstallReferrerStateListener
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:189)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:147)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:133)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:133)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at io.branch.referral.StoreReferrerUtils.getLatestValidReferrerStore(StoreReferrerUtils.java:29)
	at io.branch.referral.Branch.tryProcessNextQueueItemAfterInstallReferrer(Branch.java:1098)
	at io.branch.referral.Branch.onGoogleInstallReferrerEventsFinished(Branch.java:1072)
	at io.branch.referral.StoreReferrerGooglePlayStore.reportInstallReferrer(StoreReferrerGooglePlayStore.java:92)
	at io.branch.referral.StoreReferrerGooglePlayStore.onReferrerClientError(StoreReferrerGooglePlayStore.java:87)
	at io.branch.referral.StoreReferrerGooglePlayStore.access$000(StoreReferrerGooglePlayStore.java:13)
	at io.branch.referral.StoreReferrerGooglePlayStore$1.onInstallReferrerSetupFinished(StoreReferrerGooglePlayStore.java:62)
	at com.android.installreferrer.api.InstallReferrerClientImpl.startConnection(InstallReferrerClientImpl.java:16)
	at io.branch.referral.StoreReferrerGooglePlayStore.fetch(StoreReferrerGooglePlayStore.java:28)
	at io.branch.referral.Branch.registerAppInit(Branch.java:1988)
	at io.branch.referral.Branch.initializeSession(Branch.java:1936)
	at io.branch.referral.Branch.access$600(Branch.java:76)
	at io.branch.referral.Branch$InitSessionBuilder.init(Branch.java:3231)
	at io.branch.referral.BranchActivityLifecycleObserver.onActivityResumed(BranchActivityLifecycleObserver.java:73)
	at android.app.Application.$$robo$$android_app_Application$dispatchActivityResumed(Application.java:239)
	at android.app.Application.dispatchActivityResumed(Application.java)
	at android.app.Activity.$$robo$$android_app_Activity$onResume(Activity.java:1343)
	at android.app.Activity.onResume(Activity.java)
	at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:310)
	at android.app.Instrumentation.$$robo$$android_app_Instrumentation$callActivityOnResume(Instrumentation.java:1412)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnResume(RoboMonitoringInstrumentation.java:313)
	at android.app.Activity.$$robo$$android_app_Activity$performResume(Activity.java:7292)
	at android.app.Activity.performResume(Activity.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.robolectric.shadows._Activity_$$Reflector58.performResume(Unknown Source)
	at org.robolectric.android.controller.ActivityController.lambda$resume$5(ActivityController.java:187)
	at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:204)
	at org.robolectric.android.controller.ComponentController.invokeWhilePaused(ComponentController.java:64)
	at org.robolectric.android.controller.ActivityController.resume(ActivityController.java:182)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.startActivitySyncInternal(RoboMonitoringInstrumentation.java:116)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:35)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:40)
	at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:362)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:235)
	at androidx.fragment.app.testing.FragmentScenario$Companion.internalLaunch$fragment_testing_release(FragmentScenario.kt:590)
	at androidx.fragment.app.testing.FragmentScenario$Companion.launchInContainer(FragmentScenario.kt:561)
	at tv.caffeine.app.ui.UITests.init(UITests.kt:0)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	... 14 more
```

**Comment by gdeluna-branch** [comment]
We're tracking this for prioritization, will update when I can.

**Comment by bolot** [comment]
Any updates on this issue?

**Comment by gdeluna-branch** [comment]
This portion of the code has been updated substantially. While I have not set up any robolectric tests, please try https://central.sonatype.com/artifact/io.branch.sdk.android/library/5.6.3

You should expect that it does not crash but returns `null` instead. Please reopen if you see this continue to crash in your tests on latest.

**Comment by bolot** [comment]
Thank you! This fixed it for us. We're upgrading from 5.1.5 to 5.6.3!
