### ISSUE TITLE
Value bnc_no_value of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by kk-atom** [BranchMetrics/android-branch-deep-linking-attribution#1092]
### Describe the bug

```
org.json.JSONException: Value bnc_no_value of type java.lang.String cannot be converted to JSONObject
                                         	at org.json.JSON.typeMismatch(JSON.java:112)
                                         	at org.json.JSONObject.<init>(JSONObject.java:172)
                                         	at org.json.JSONObject.<init>(JSONObject.java:185)
                                         	at io.branch.referral.PrefHelper.getReferringURLQueryParameters(PrefHelper.java:745)
                                         	at io.branch.referral.ReferringUrlUtility.<init>(ReferringUrlUtility.kt:15)
                                         	at io.branch.referral.ServerRequest.onPreExecute(ServerRequest.java:683)
                                         	at io.branch.referral.ServerRequestInitSession.onPreExecute(ServerRequestInitSession.java:191)
                                         	at io.branch.referral.ServerRequestRegisterOpen.onPreExecute(ServerRequestRegisterOpen.java:44)
                                         	at io.branch.referral.Branch$BranchPostTask.onPreExecute(Branch.java:2390)
                                         	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:724)
                                         	at io.branch.referral.BranchAsyncTask.executeTask(BranchAsyncTask.java:21)
                                         	at io.branch.referral.Branch.executeTimedBranchPostTask(Branch.java:1756)
                                         	at io.branch.referral.Branch.processNextQueueItem(Branch.java:1736)
                                         	at io.branch.referral.Branch$4.onStrongMatchCheckFinished(Branch.java:2105)
                                         	at io.branch.referral.BranchStrongMatchHelper.updateStrongMatchCheckFinished(BranchStrongMatchHelper.java:149)
                                         	at io.branch.referral.BranchStrongMatchHelper.checkForStrongMatch(BranchStrongMatchHelper.java:76)
                                         	at io.branch.referral.Branch.performCookieBasedStrongMatch(Branch.java:2100)
                                         	at io.branch.referral.Branch.onAdsParamsFetchFinished(Branch.java:1064)
                                         	at io.branch.referral.GAdsPrefetchTask.onPostExecute(GAdsPrefetchTask.java:73)
                                         	at io.branch.referral.GAdsPrefetchTask.onPostExecute(GAdsPrefetchTask.java:18)
                                         	at android.os.AsyncTask.finish(AsyncTask.java:771)
                                         	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
                                         	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
                                         	at android.os.Handler.dispatchMessage(Handler.java:106)
                                         	at android.os.Looper.loopOnce(Looper.java:201)
                                         	at android.os.Looper.loop(Looper.java:288)
                                         	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                         	at java.lang.reflect.Method.invoke(Native Method)
                                         	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Steps to reproduce

1.
2.
3.

### Expected behavior

I should not see such error in logs.

### SDK Version

5.6.1

### Make and Model

Pixel 4a

### OS

13

**Comment by gdeluna-branch** [comment]
Thanks for raising this. We're currently fixing up our logging so stay tuned.

**Comment by gdeluna-branch** [comment]
Released as of https://central.sonatype.com/artifact/io.branch.sdk.android/library/5.6.3
