### ISSUE TITLE
Getting ANR while initialising the SDK

### ISSUE THREAD

**Issue by empquin** [BranchMetrics/android-branch-deep-linking-attribution#1140]
### Describe the bug

Hi,

We're facing ANR issues while initialising the branch SDK with getAutoInstance(). And our playstore app uses branch SDK v5.2.0. Here is the ANR report.

main (runnable):tid=1 systid=27815 
       at io.branch.referral.Branch.<init>(Branch.java:409)
       at io.branch.referral.Branch.initBranchSDK(Branch.java:437)
       at io.branch.referral.Branch.getAutoInstance(Branch.java:467)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1242)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7185)
       at android.app.ActivityThread.access$1500(ActivityThread.java:265)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2152)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8185)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

And we did test it on the latest 5.7.2 release as well, and we see this below problem! Please kindly let us know for any solution. Thanks in advance.

StrictMode policy violation; ~duration=400 ms: android.os.strictmode.DiskReadViolation
at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7719)
at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
at java.io.File.exists(File.java:813)
at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:743)
at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:734)
at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:690)
at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:915)
at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:537)
at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:196)
at io.branch.referral.PrefHelper.<init>(PrefHelper.java:181)
at io.branch.referral.PrefHelper.getInstance(PrefHelper.java:196)
at io.branch.referral.Branch.<init>(Branch.java:317)
at io.branch.referral.Branch.initBranchSDK(Branch.java:345)
at io.branch.referral.Branch.getAutoInstance(Branch.java:387)

StrictMode policy violation; ~duration=400 ms: android.os.strictmode.DiskReadViolation
at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:275)
at android.app.SharedPreferencesImpl.edit(SharedPreferencesImpl.java:368)
at io.branch.referral.PrefHelper.<init>(PrefHelper.java:182)
at io.branch.referral.PrefHelper.getInstance(PrefHelper.java:196)
at io.branch.referral.Branch.<init>(Branch.java:317)
at io.branch.referral.Branch.initBranchSDK(Branch.java:345)
at io.branch.referral.Branch.getAutoInstance(Branch.java:387)

StrictMode policy violation; ~duration=392 ms: android.os.strictmode.DiskReadViolation
at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7719)
at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
at java.io.File.exists(File.java:813)
at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:743)
at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:734)
at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:690)
at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:915)
at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:537)
at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:196)
at io.branch.referral.ServerRequestQueue.<init>(ServerRequestQueue.java:87)
at io.branch.referral.ServerRequestQueue.getInstance(ServerRequestQueue.java:65)
at io.branch.referral.Branch.<init>(Branch.java:323)
at io.branch.referral.Branch.initBranchSDK(Branch.java:345)
at io.branch.referral.Branch.getAutoInstance(Branch.java:387)

StrictMode policy violation; ~duration=391 ms: android.os.strictmode.DiskReadViolation
at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1659)
at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:275)
at android.app.SharedPreferencesImpl.edit(SharedPreferencesImpl.java:368)
at io.branch.referral.ServerRequestQueue.<init>(ServerRequestQueue.java:88)
at io.branch.referral.ServerRequestQueue.getInstance(ServerRequestQueue.java:65)
at io.branch.referral.Branch.<init>(Branch.java:323)
at io.branch.referral.Branch.initBranchSDK(Branch.java:345)
at io.branch.referral.Branch.getAutoInstance(Branch.java:387)
                                                                                            

### Steps to reproduce

Call Branch.getAutoInstance(this) onCreate of the Application class.

### Expected behavior

-

### SDK Version

5.2.0

### Make and Model

On prod, this is happening on many devices including Samsung, Vivo, Oppo etc..

### OS

11 and above

**Comment by annamorgiel** [comment]
my Team is also facing the same issue on version 5.8.0,  mainly on Xiaomi, Motorola and similar devices, happening 100% in the background

**Comment by rovkinmax** [comment]
the same problem
