### ISSUE TITLE
Branch links are sometimes clickable, sometimes not in Android  (using Oreo 8.0)

### ISSUE THREAD

**Issue by rashidfiverivers** [BranchMetrics/android-branch-deep-linking-attribution#806]
Facing this issue on Android 8.0 and some other devices as well. 
On clicking dialog disappears and and nothing opens. On clicking it 2nd or 3rd time, it opens that sometimes. Facing Strange behavior. 

Using 
    **implementation 'io.branch.sdk.android:library:4.3.2'**

**Comment by rashidfiverivers** [comment]
Getting this:

`2020-02-10 12:57:19.110 1046-1046/com.frt.ballogyapp V/AudioManager: playSoundEffect   effectType: 0
2020-02-10 12:57:19.110 1046-1046/com.frt.ballogyapp E/invoke:: onChannelSelected
2020-02-10 12:57:19.631 1046-1248/com.frt.ballogyapp W/libEGL: EGLNativeWindowType 0x7235fef010 disconnect failed
2020-02-10 12:57:19.685 1046-1046/com.frt.ballogyapp W/System.err: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter error
2020-02-10 12:57:19.685 1046-1046/com.frt.ballogyapp W/System.err:     at com.frt.ballogyapp.utils.GeneralUtils$Companion$inviteFriends$1.onLinkShareResponse(Unknown Source:12)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.indexing.BranchUniversalObject$LinkShareListenerWrapper.onLinkShareResponse(BranchUniversalObject.java:980)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.referral.ShareLinkManager.shareWithClient(ShareLinkManager.java:310)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.referral.ShareLinkManager.access$700(ShareLinkManager.java:31)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.referral.ShareLinkManager$3.onLinkCreate(ShareLinkManager.java:283)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.referral.ServerRequestCreateUrl.onRequestSucceeded(ServerRequestCreateUrl.java:126)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.referral.Branch$BranchPostTask.onPostExecute(Branch.java:3126)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.referral.Branch$BranchPostTask.onPostExecute(Branch.java:2963)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:727)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at android.os.AsyncTask.-wrap1(Unknown Source:0)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:744)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:108)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at android.os.Looper.loop(Looper.java:166)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7529)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-02-10 12:57:19.687 1046-1046/com.frt.ballogyapp W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
2020-02-10 12:57:19.687 1046-1046/com.frt.ballogyapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
2020-02-10 12:57:19.688 1046-1046/com.frt.ballogyapp E/invoke:: onShareLinkDialogDismissed
2020-02-10 12:57:19.689 1046-1046/com.frt.ballogyapp W/InputMethodManager: startInputReason = 1
2020-02-10 12:57:19.697 1046-1046/com.frt.ballogyapp E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
2020-02-10 12:57:19.697 1046-1046/com.frt.ballogyapp E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
2020-02-10 12:57:28.334 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: Message: Unknown MediaEventType(6), ext1=0, ext2=0x0
2020-02-10 12:57:28.334 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1204] callback app listenerNotNull=1, send=1
2020-02-10 12:57:28.334 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1216] callback application
2020-02-10 12:57:42.451 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: Message: Unknown MediaEventType(6), ext1=0, ext2=0x0
2020-02-10 12:57:42.452 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1204] callback app listenerNotNull=1, send=1
2020-02-10 12:57:42.452 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1216] callback application
2020-02-10 12:57:56.582 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: Message: Unknown MediaEventType(6), ext1=0, ext2=0x0
2020-02-10 12:57:56.582 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1204] callback app listenerNotNull=1, send=1
2020-02-10 12:57:56.582 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1216] callback application
2020-02-10 12:58:10.697 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: Message: Unknown MediaEventType(6), ext1=0, ext2=0x0
2020-02-10 12:58:10.697 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1204] callback app listenerNotNull=1, send=1
2020-02-10 12:58:10.697 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1216] callback application
2020-02-10 12:58:24.822 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: Message: Unknown MediaEventType(6), ext1=0, ext2=0x0
2020-02-10 12:58:24.822 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1204] callback app listenerNotNull=1, send=1
2020-02-10 12:58:24.822 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1216] callback application
2020-02-10 12:58:38.943 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: Message: Unknown MediaEventType(6), ext1=0, ext2=0x0
2020-02-10 12:58:38.943 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1204] callback app listenerNotNull=1, send=1
2020-02-10 12:58:38.943 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1216] callback application
2020-02-10 12:58:53.063 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: Message: Unknown MediaEventType(6), ext1=0, ext2=0x0
2020-02-10 12:58:53.063 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1204] callback app listenerNotNull=1, send=1
2020-02-10 12:58:53.063 1046-1524/com.frt.ballogyapp D/MediaPlayerNative: [notify] : [1216] callback application
`

**Comment by rashidfiverivers** [comment]
```
2020-02-10 12:57:19.110 1046-1046/com.frt.ballogyapp E/invoke:: onChannelSelected
2020-02-10 12:57:19.631 1046-1248/com.frt.ballogyapp W/libEGL: EGLNativeWindowType 0x7235fef010 disconnect failed
2020-02-10 12:57:19.685 1046-1046/com.frt.ballogyapp W/System.err: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter error
2020-02-10 12:57:19.685 1046-1046/com.frt.ballogyapp W/System.err:     at com.frt.ballogyapp.utils.GeneralUtils$Companion$inviteFriends$1.onLinkShareResponse(Unknown Source:12)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.indexing.BranchUniversalObject$LinkShareListenerWrapper.onLinkShareResponse(BranchUniversalObject.java:980)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.referral.ShareLinkManager.shareWithClient(ShareLinkManager.java:310)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.referral.ShareLinkManager.access$700(ShareLinkManager.java:31)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.referral.ShareLinkManager$3.onLinkCreate(ShareLinkManager.java:283)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.referral.ServerRequestCreateUrl.onRequestSucceeded(ServerRequestCreateUrl.java:126)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.referral.Branch$BranchPostTask.onPostExecute(Branch.java:3126)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at io.branch.referral.Branch$BranchPostTask.onPostExecute(Branch.java:2963)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:727)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at android.os.AsyncTask.-wrap1(Unknown Source:0)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:744)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:108)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at android.os.Looper.loop(Looper.java:166)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7529)
2020-02-10 12:57:19.686 1046-1046/com.frt.ballogyapp W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-02-10 12:57:19.687 1046-1046/com.frt.ballogyapp W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
2020-02-10 12:57:19.687 1046-1046/com.frt.ballogyapp W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
2020-02-10 12:57:19.688 1046-1046/com.frt.ballogyapp E/invoke:: onShareLinkDialogDismissed
2020-02-10 12:57:19.689 1046-1046/com.frt.ballogyapp W/InputMethodManager: startInputReason = 1
2020-02-10 12:57:19.697 1046-1046/com.frt.ballogyapp E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
2020-02-10 12:57:19.697 1046-1046/com.frt.ballogyapp E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
```

**Comment by rashidfiverivers** [comment]
There was some Kotlin issue. I converted the code to JAVA and everything is perfect now.
