### ISSUE TITLE
Branch.enableLogging ( NoSuchMethodErr Fatal Exception) 

### ISSUE THREAD

**Issue by medha742** [BranchMetrics/android-branch-deep-linking-attribution#863]
Hello Everyone 

Receiving this crash in release build at Branch.enableLogging ( Application class) , Seems like a proguard issue . Is there any proguard rule that needs to be added for branch integration?

Fatal Exception: java.lang.NoSuchMethodError: No static method b(Ljava/lang/String;)V in class Lj/a/b/u; or its super classes (declaration of 'j.a.b.u' appears in /data/app/com.shiprocket.shiprocket-<some_key>-w==/base.apk!classes2.dex)
       at io.branch.referral.Branch.enableLogging(Branch.java:2695)
       at com.shiprocket.shiprocket.ShipRocket.initBranchIO(ShipRocket.java:109)
       at com.shiprocket.shiprocket.ShipRocket.onCreate(ShipRocket.java:84)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1127)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6111)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7025)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCal

**Comment by jf-branch** [comment]
Hey @medha742 

This does in fact seem to be a proguard blocker. Our standard protocol regarding proguard is as followed: https://help.branch.io/developers-hub/docs/android-full-reference#proguard-settings-for-leveraging-branchs-pooled-matching 

Please let us know if you were able to resolve this and if not, how we can help support.
