### ISSUE TITLE
Crash ConcurrentModificationException from Branch.extractAppLink 

### ISSUE THREAD

**Issue by AlonParker** [BranchMetrics/android-branch-deep-linking-attribution#900]
Hello,
Crashes from production:
branchVersion = '5.0.3'

android.util.ArrayMap.put (ArrayMap.java:502)
android.os.BaseBundle.putBoolean (BaseBundle.java:570)
android.content.Intent.putExtra (Intent.java:8361)
**io.branch.referral.Branch.extractAppLink (Branch.java:2986)
io.branch.referral.Branch.readAndStripParam (Branch.java:1087)
io.branch.referral.Branch.onIntentReady (Branch.java:2088)
io.branch.referral.BranchActivityLifecycleObserver.onActivityResumed (BranchActivityLifecycleObserver.java:65)**
android.app.Application.dispatchActivityResumed (Application.java:239)
android.app.Activity.onResume (Activity.java:1343)
androidx.fragment.app.FragmentActivity.onResume (FragmentActivity.java:455)
moxy.MvpAppCompatActivity.onResume (MvpAppCompatActivity.java:39)
android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1413)
android.app.Activity.performResume (Activity.java:7292)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:3814)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3854)
android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:51)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:145)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1816)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:6735)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)

**Comment by evgeni-shafran** [comment]
Any updates on this? this crash attributes to 20% of the crashes of our last release

**Comment by Kurisasa** [comment]
Same crash, anything yet?

**Comment by jf-branch** [comment]
Hey @AlonParker 

Wanted to follow up on this and see if you were still experiencing this issue. 

If so, could you help us by providing additional information so we can reproduce on our end? 

Thank you,
Justin

**Comment by blinkev** [comment]
@jf-branch Hi! It's still there, the top crash in our production. branchVersion = '5.0.11'. What kind of information do you want?

**Comment by alaegin** [comment]
The same issue is in a large application with millions of users.

**Comment by blinkev** [comment]
Any update on that? Caught it a minute ago on a debug build

2022-07-15 09:56:55.434 13579-13579/com.xxx.androidapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.xxxapp, PID: 13579
    java.lang.RuntimeException: Unable to resume activity {com.xxx.xxxapp/com.xxx.android.start.StartActivity}: java.util.ConcurrentModificationException
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4300)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4332)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7561)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
     Caused by: java.util.ConcurrentModificationException
        at android.util.ArrayMap.put(ArrayMap.java:608)
        at android.os.BaseBundle.putBoolean(BaseBundle.java:584)
        at android.content.Intent.putExtra(Intent.java:8837)
        at io.branch.referral.Branch.extractAppLink(Branch.java:2870)
        at io.branch.referral.Branch.readAndStripParam(Branch.java:975)
        at io.branch.referral.Branch.onIntentReady(Branch.java:1979)
        at io.branch.referral.BranchActivityLifecycleObserver.onActivityResumed(BranchActivityLifecycleObserver.java:65)
        at android.app.Application.dispatchActivityResumed(Application.java:461)
        at android.app.Activity.dispatchActivityResumed(Activity.java:1296)
        at android.app.Activity.onResume(Activity.java:1833)
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:434)
        at moxy.MvpAppCompatActivity.onResume(MvpAppCompatActivity.java:39)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
        at android.app.Activity.performResume(Activity.java:8050)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4290)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4332) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7561) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
