### ISSUE TITLE
Crash: Branch.java line 2747 - io.branch.referral.Branch$InitSessionBuilder.<init>

### ISSUE THREAD

**Issue by w3b-amit** [BranchMetrics/android-branch-deep-linking-attribution#901]
We are getting on crash on Branch android SDK. I am sharing the log here, please look into it.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Activity io.branch.referral.Branch.getCurrentActivity()' on a null object reference
       at io.branch.referral.Branch$InitSessionBuilder.<init>(Branch.java:2747)
       at io.branch.referral.Branch$InitSessionBuilder.<init>(Branch.java:2738)
       at io.branch.referral.Branch.sessionBuilder(Branch.java:2922)
       at w3bminds.engVarta.app.Activities.Splash$4.run(Splash.java:195)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by kshandilya-branch** [comment]
Have you added the Application class in your Manifest.xml file?

**Comment by w3b-amit** [comment]
Yes, we have added our application sub-class to the manifests applications
tag.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/05/21,
11:46:08 am

**Comment by jf-branch** [comment]
Hey @w3b-amit 

Are you still facing this issue? Was this resolved with a more recent release? For 5.0.9 we added some NPE handling to address issues like this, but we want to confirm that was the fix?

Thank you,
Justin

**Comment by jf-branch** [comment]
Hey @Nadeembhat-Cohesion  can you confirm youre are following the sessionBuilders init and reinit properly on both your activity's onStart and onNewIntent as stated: https://help.branch.io/developers-hub/docs/android-basic-integration#initialize-branch?

**Comment by Nadeembhat-Cohesion** [comment]
@jf-branch the code is below that i am using in my launcher activity
` override fun onStart() {
        super.onStart()
        // Branch init
        Branch.sessionBuilder(this).withCallback(branchListener).withData(this.intent?.data).init()
    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        this.intent = intent
        // Branch reinit (in case Activity is already in foreground when Branch link is clicked)
        Branch.sessionBuilder(this).withCallback(branchListener).reInit()
    }

    object branchListener : BranchReferralInitListener {
        override fun onInitFinished(referringParams: JSONObject?, error: BranchError?) {
            if (error == null) {
                Log.i("BRANCH SDK", referringParams.toString())
                // Retrieve deeplink keys from 'referringParams' and evaluate the values to determine where to route the user
                // Check '+clicked_branch_link' before deciding whether to use your Branch routing logic
            } else {
                Log.e("BRANCH SDK", error.message)
            }
        }
    }`

**Comment by Nadeembhat-Cohesion** [comment]
@jf-branch  It got fixed its own. Thank you for Quick Reply

**Comment by andreibacalu** [comment]
hello! this issue still happens on our side, using version 5.20.0:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Activity io.branch.referral.k.i0()' on a null object reference
       at io.branch.referral.Branch$InitSessionBuilder.<init>(Branch.java:2359)
       at io.branch.referral.Branch$InitSessionBuilder.<init>(Branch.java:2349)
       at io.branch.referral.Branch.sessionBuilder(Branch.java:2595)
       at com.aerlingus.MainActivity.onStart(MainActivity.java:996)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1699)
       at android.app.Activity.performStart(Activity.java:9562)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4744)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:214)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:194)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:166)
       at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:101)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3150)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loopOnce(Looper.java:273)
       at android.os.Looper.loop(Looper.java:363)
       at android.app.ActivityThread.main(ActivityThread.java:10060)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

In order to avoid it we had to add a null check in onStart():
Branch branch = Branch.getInstance();
if (branch != null) {
             Branch.sessionBuilder(this);
...

Seems like it is a race condition between the initialisation called in application and the code called in onStart. Any other solution ideas?
