### ISSUE TITLE
Crash on start with liveKey / testKey / useTestInstance in branch.json

### ISSUE THREAD

**Issue by Jared-D** [BranchMetrics/android-branch-deep-linking-attribution#912]
I'm using Android Branch SDK version 5.0.8 (via React Native Branch SDK version 5.0.3)

Error and stack trace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.cool.coolapp, PID: 5670
    java.lang.RuntimeException: Unable to create application com.cool.coolapp.MainApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at io.branch.referral.BranchJsonConfig.getBranchKey(BranchJsonConfig.java:123)
        at io.branch.referral.BranchUtil.readBranchKey(BranchUtil.java:90)
        at io.branch.referral.Branch.getAutoInstance(Branch.java:454)
        at io.branch.rnbranch.RNBranchModule.getAutoInstance(RNBranchModule.java:101)
        at com.cool.coolapp.MainApplication.onCreate(MainApplication.java:129)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
```
This is the same error described in the React Native Branch SDK repository issue: https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/643
> The logic around useTestInstance has a bug. The getUseTestInstance() returns null and the return type is Boolean, so can't be unboxed in the conditional.

The obvious fix would be to change `Branch-SDK/src/main/java/io/branch/referral/BranchJsonConfig.java` from
```java
    public @Nullable Boolean getUseTestInstance() {
        if (isValid(BranchJsonKey.useTestInstance)) return null;
        ...
```
to
```java
    public @Nullable Boolean getUseTestInstance() {
        if (!isValid(BranchJsonKey.useTestInstance)) return null;
        ...
```
but I don't know if that has other ramifications that will break things.

**Comment by gauravpassi** [comment]
any update?

**Comment by KDederichs** [comment]
+1
Having the same issue here, please fix this asap.
Can't be that that's open for over two weeks....

**Comment by tkcarnage** [comment]
still not fixed for sure.

**Comment by ziyoshams** [comment]
Anyone knows a workaround?

**Comment by KDederichs** [comment]
you either don't use the json file for configuration or use an older version that's still working.
Those are the options here I think

**Comment by ziyoshams** [comment]
🤦

**Comment by ziyoshams** [comment]
actually, using `branchKey` instead of `liveKey` or `testKey` fixes this.
