### ISSUE TITLE
NPE in Branch.addExtraInstrumentationData(..)

### ISSUE THREAD

**Issue by Jeff11** [BranchMetrics/android-branch-deep-linking-attribution#922]
Branch version 5.0.9

An Amazon KFSUWI device on Android 5.1.1 is crashing very often with following stacktrace:

```
Caused by java.lang.NullPointerException: Attempt to read from field 'j$.util.concurrent.ConcurrentHashMap f0.a.a.c.q' on a null object reference
       at io.branch.referral.Branch.addExtraInstrumentationData(Branch.java:2469)
       at io.branch.referral.BranchPostTask.doInBackground(BranchPostTask.java:39)
       at io.branch.referral.BranchPostTask.doInBackground(BranchPostTask.java:17)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by sxkumaravel** [comment]
Have the same issue after updating to 5.0.9. Additional information regarding the crash.

Caused by java.lang.NullPointerException: Attempt to read from field 'java.util.concurrent.ConcurrentHashMap io.branch.referral.b.m' on a null object reference
       at io.branch.referral.Branch.addExtraInstrumentationData(Branch.java:2469)
       at io.branch.referral.BranchPostTask.doInBackground(BranchPostTask.java:39)
       at io.branch.referral.BranchPostTask.doInBackground(BranchPostTask.java:17)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

18739 crash events affecting 14 users
![Screen Shot 2021-07-30 at 12 49 11 PM](https://user-images.githubusercontent.com/10620508/127685747-e6bc4baf-e826-4a17-a7ef-068f0ac13607.png)

**Comment by Jeff11** [comment]
Duplicate of https://github.com/BranchMetrics/android-branch-deep-linking-attribution/issues/913
