### ISSUE TITLE
Crash after updating to 5.0.10

### ISSUE THREAD

**Issue by yuvalgnessin-qz** [BranchMetrics/android-branch-deep-linking-attribution#926]
After upgrading from 5.0.9 to 5.0.10 we started seeing this crash come through crashlytics at a very high volume:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.app.Activity.getReferrer()' on a null object reference
       at androidx.core.app.ActivityCompat.getReferrer(ActivityCompat.java:333)
       at io.branch.referral.Branch$InitSessionBuilder.init(Branch.java:2876)
```

This crash is coming from the code below. In the line right above the crash source, there is a check for `activity` being null, so clearly its nullability is expected. However, regardless of that check, it is passed to `ActivityCompat.getReferrer` which crashes when it's null.

```java
        public void init() {
            ...

            Activity activity = branch.getCurrentActivity();
            Intent intent = activity != null ? activity.getIntent() : null; // It's expected that activity might be null

            if (ActivityCompat.getReferrer(activity) != null) { // throws NPE if activity is null
                PrefHelper.getInstance(activity).setInitialReferrer(ActivityCompat.getReferrer(activity).toString());
            }

            ...
         }
```

Unfortunately this crash is happening at a high enough volume for us that we are forced to hotfix a downgrade to 5.0.9. Please fix this as quickly as you can.

Thank you very much!

**Comment by yuvalgnessin-qz** [comment]
Fixed by https://github.com/BranchMetrics/android-branch-deep-linking-attribution/pull/927

Thanks!
