### ISSUE TITLE
System.err - Deeplink click WarmLaunch(Bringing app from Background to Foreground) with Non-Launcher Activity init 

### ISSUE THREAD

**Issue by ercanpinar** [BranchMetrics/android-branch-deep-linking-attribution#949]
v5.0.15
Click a deeplink while the app is staying on background

Used Init Listener: Branch.BranchReferralInitListener
only onStart function is getting called. onNewIntent is not getting called.

1. SDK init error observed : Error: Intra-app linking (i.e. session reinitialization) requires an intent flag, "branch_force_new_session".

 2. SDK init success observed : referringParams: {"+clicked_branch_link":false,"+is_first_session":false}
onInitFinished: BRANCH SDK onStart INIT - onInitFinished - referringParams: {"+clicked_branch_link":false,"+is_first_session":false}
W/System.err:     at io.branch.referral.ServerRequestRegisterOpen.onRequestSucceeded(ServerRequestRegisterOpen.java:75)
W/System.err:     at io.branch.referral.Branch$BranchPostTask.onRequestSuccess(Branch.java:2388)
W/System.err:     at io.branch.referral.Branch$BranchPostTask.onPostExecuteInner(Branch.java:2299)
W/System.err:     at io.branch.referral.Branch$BranchPostTask.onPostExecute(Branch.java:2285)
W/System.err:     at io.branch.referral.Branch$BranchPostTask.onPostExecute(Branch.java:2244)

Ps: Issue 1 has been reported and mentioned on the page:  LauncherActivity vs other Activities
https://help.branch.io/developers-hub/docs/android-basic-integration

Thanks

**Comment by ercanpinar** [comment]
I have found the issue. The intent data must be carrying the only Branch SDK intent data When you are feeding the Branch SDK init or reInit function. if you manipulate the intent data, it will be throwing the error in the SDK. I had to debug the SDK step by step to capture this problem. I would expect to receive some error message instead of SDK exception without any info in it. Thanks
