### ISSUE TITLE
Getting ANR on io.branch.referral.Branch.executeTimedBranchPostTask (Branch.java:1692)

### ISSUE THREAD

**Issue by lovepreetSinghElectricpe** [BranchMetrics/android-branch-deep-linking-attribution#972]
Type = "main" prio=5 tid=1 TimedWaiting
Log =
  at sun.misc.Unsafe.park (Native method)
  at java.util.concurrent.locks.LockSupport.parkNanos (LockSupport.java:230)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos (AbstractQueuedSynchronizer.java:1063)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos (AbstractQueuedSynchronizer.java:1358)
  at java.util.concurrent.CountDownLatch.await (CountDownLatch.java:278)
  at io.branch.referral.Branch.executeTimedBranchPostTask (Branch.java:1692)
  at io.branch.referral.Branch.processNextQueueItem (Branch.java:1670)
  at io.branch.referral.Branch$3.onStrongMatchCheckFinished (Branch.java:1966)
  at io.branch.referral.BranchStrongMatchHelper.updateStrongMatchCheckFinished (BranchStrongMatchHelper.java:149)
  at io.branch.referral.BranchStrongMatchHelper.checkForStrongMatch (BranchStrongMatchHelper.java:76)
  at io.branch.referral.Branch.performCookieBasedStrongMatch (Branch.java:1961)
  at io.branch.referral.Branch.onAdsParamsFetchFinished (Branch.java:968)
  at io.branch.referral.GAdsPrefetchTask.onPostExecute (GAdsPrefetchTask.java:73)
  at io.branch.referral.GAdsPrefetchTask.onPostExecute (GAdsPrefetchTask.java:18)
  at android.os.AsyncTask.finish (AsyncTask.java:771)
  at android.os.AsyncTask.access$900 (AsyncTask.java:199)
  at android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:788)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:257)
  at android.app.ActivityThread.main (ActivityThread.java:8222)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:626)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1016)

**Comment by lovepreetSinghElectricpe** [comment]
Got this error on mainly Vivo devices in Android 11.

**Comment by giangpham96** [comment]
I have the same issue with Samsung & Xiaomi. 
library version: 5.1.1

```
main (native): tid=1 systid=22985
#00 pc 0x4b48c libc.so 
#01 pc 0x1af92c libart.so 
#02 pc 0x669b0c libart.so 
#03 pc 0x6698fc libart.so 
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:887)
       at io.branch.referral.Branch.executeTimedBranchPostTask(Branch.java:1711)
       at io.branch.referral.Branch.processNextQueueItem(Branch.java:1685)
       at io.branch.referral.Branch$BranchPostTask$1.run(Branch.java:2332)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7698)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```
