### ISSUE TITLE
PrefHelper.java line 168  (io.branch.referral.PrefHelper.<init>)

### ISSUE THREAD

**Issue by NitinPraksash9911** [BranchMetrics/android-branch-deep-linking-attribution#987]
**Issue**:
`main (waiting): tid=1 systid=13131 
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:279)
       at android.app.SharedPreferencesImpl.edit(SharedPreferencesImpl.java:368)
       at io.branch.referral.PrefHelper.<init>(PrefHelper.java:168)
       at io.branch.referral.PrefHelper.getInstance(PrefHelper.java:182)
       at io.branch.referral.Branch.<init>(Branch.java:394)
       at io.branch.referral.Branch.initBranchSDK(Branch.java:423)
       at io.branch.referral.Branch.getAutoInstance(Branch.java:453)
       at app.geochat.revamp.application.Trell.onCreate(Trell.java:239)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7506)
       at android.app.ActivityThread.access$1600(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`

**Note:** while calling this->    ` Branch.getAutoInstance(this).enableFacebookAppLinkCheck()`

**Devices**:

Brand:samsung
Model:Galaxy M31
Version:Android 12

Brand:samsung
Model:Galaxy Note20 Ultra 5G
Version:Android 11

**Comment by nsingh-branch** [comment]
This method has been deprecated and removed as of v5.7.0.
